# Database config
spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  liquibase:
    changeLog: "classpath:/db/changelog/changelog-master.xml"
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Actuator config
management:
  endpoints:
    web:
      exposure:
        include: beans, metrics, info, health, loggers, readiness

# Misc
secretkeeper:
  trace: true
