openapi: 3.0.0
info:
  title: Secret Keeper Api
  description: An api that helps manage your secrets.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: credentials
    description: Manage your credentials
paths:
  /credentials:
    post:
      tags:
        - credentials
      summary: Add a new credential
      description: ''
      operationId: newCredential
      requestBody:
        description: Credential that needs to be stored
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialRequest'
            example:
              credential:
                summary: Example of a credential
                value:
                  url: www.gmail.com
                  username: john.doe@gmail.com
                  password: password
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/CredentialDetails'
    get:
      tags:
        - credentials
      summary: ''
      operationId: getCredentials
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CredentialDetails'
              examples: {}
            application/xml:
              schema:
                type: object
                properties: {}
      description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: url
        - schema:
            type: string
          in: query
          name: username
components:
  schemas:
    CredentialDetails:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
        username:
          type: string
        password:
          type: string
    CredentialRequest:
      type: object
      properties:
        url:
          type: string
        username:
          type: string
        password:
          type: string
      required:
        - url
        - username
        - password
